In [42]:
import numpy as np
import pandas as pd
df=pd.read_csv("cardekho_dataset.csv")
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.shape
print(df.info())
print(df.isnull().sum() * 100 / len(df))

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  str
 2   brand              15411 non-null  str
 3   model              15411 non-null  str
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  str
 7   fuel_type          15411 non-null  str
 8   transmission_type  15411 non-null  str
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), str(6)
memory usage: 1.6 MB
None
Unnamed: 0           0.0
car_name             0.0
brand                0.0
model                0.0
vehicle_age          0.0
km_driven            0.0
seller_type          0.0
fuel_type            0.0
transmission_type    0.0
mileage              0.0
engine               0.0
max_power            0.0
seats                0.0
selling_price        0.0
dtype: float64

In [5]:
df["selling_price"].isnull().sum()

np.int64(0)

In [18]:
print(df["mileage"].isnull().sum())
print(df["mileage"].dtype)
print(df["mileage"].nunique())
print(df["engine"].isnull().sum())
print(df["engine"].dtype)
print(df["engine"].nunique())

0
float64
411
0
int64
110

In [25]:
print(df[(df["selling_price"] >= 999999999) & (df["selling_price"] <= 10000)])
print(df.columns.duplicated().sum())
print(df.shape)

Empty DataFrame
Columns: [Unnamed: 0, car_name, brand, model, vehicle_age, km_driven, seller_type, fuel_type, transmission_type, mileage, engine, max_power, seats, selling_price]
Index: []
0
(15411, 14)

In [25]:
df["transmission_type"]=df["transmission_type"].astype(str)
df["transmission_type"].dtype
df["transmission_type"]=df["transmission_type"].str.strip().str.title()
df["transmission_type"]=df["transmission_type"].replace({"Automatic": 1, "Manual": 0})
print(df["transmission_type"].head(20))

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     0
10    0
11    0
12    1
13    0
14    0
15    1
16    0
17    0
18    0
19    0
Name: transmission_type, dtype: str

In [ ]:
a=pd.get_dummies(df["fuel_type"],drop_first=True)
b=pd.concat([df,a],axis=1)
b.drop("fuel_type",axis=1,inplace=True)
b.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,transmission_type,mileage,engine,max_power,seats,selling_price,Diesel,Electric,LPG,Petrol
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Manual,19.70,796,46.30,5,120000,False,False,False,True
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Manual,18.90,1197,82.00,5,550000,False,False,False,True
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Manual,17.00,1197,80.00,5,215000,False,False,False,True
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Manual,20.92,998,67.10,5,226000,False,False,False,True
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Manual,22.77,1498,98.59,5,570000,True,False,False,False

In [45]:
df.columns.tolist()

['Unnamed: 0',
 'car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'seller_type',
 'fuel_type',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [47]:
from sklearn.model_selection import train_test_split
x=df.drop("selling_price", axis=1)
y=df["selling_price"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(12328, 13) (3083, 13) (12328,) (3083,)

In [48]:
from sklearn.metrics import mean_absolute_error
baseline_pred=np.mean(y_train)
y_pred_baseline=np.repeat(baseline_pred,len(y_test))
baseline_mae=mean_absolute_error(y_test,y_pred_baseline)
print(f"Baseline MAE: ₹{round(baseline_mae)}")

Baseline MAE: ₹468748